development:
  adapter: postgresql
  encoding: unicode
  database: donorsfly_dev
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: donorsfly_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: donorsfly_prod
  pool: 5
